import type { LiveRegionVariant } from '@pitchfork-ui/core';

import {
  Component,
  Element,
  Event,
  EventEmitter,
  h,
  Host,
  Method,
  Prop,
  State,
} from '@stencil/core';

export type PfToasterPlacement = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';

export interface PfToastOptions {
  variant?: LiveRegionVariant;
  heading?: string;
  description?: string;
  /** Milliseconds before it dismisses itself. `0` keeps it until dismissed. */
  duration?: number;
  /** Render the dismiss button. Defaults to true. */
  dismissable?: boolean;
}

interface Entry extends PfToastOptions {
  id: string;
}

/**
 * The region toasts appear in, and the queue behind them.
 *
 * This is the one place the elements layer takes options rather than child
 * elements, against the rule in `WEB-COMPONENTS-PLAN.md` §2.1 — because a
 * toast is not data the consumer is rendering, it is an event that happened.
 * React expresses that with a context provider and a module-level `toast()`;
 * the equivalent for a custom element is a method on the region, since a
 * consumer calling `toast()` three times from an event handler cannot
 * reasonably be asked to maintain a list of children for it.
 *
 * Declarative use still works: anything slotted in is laid out in the stack
 * alongside the queue, which is how a notification that is part of the page
 * rather than a response to an action is placed here.
 *
 * The region itself is not a live region. Each `pf-notification` is one
 * already, so marking the container as well would announce every toast twice.
 *
 * @slot - notifications placed in the stack declaratively.
 * @part stack - the positioned container.
 */
@Component({
  tag: 'pf-toaster',
  styleUrl: 'pf-toaster.css',
  shadow: true,
})
export class PfToaster {
  @Element() el!: HTMLElement;

  /** Which corner the stack sits in. Reflected; the stylesheet positions on it. */
  @Prop({ reflect: true }) placement: PfToasterPlacement = 'top-right';

  /** Auto-dismiss delay for toasts that do not set their own. `0` disables it. */
  @Prop() duration = 4000;

  /** Fires when a toast has left, with the id `toast()` returned. */
  @Event() pfToastDismiss!: EventEmitter<{ id: string }>;

  @State() entries: Entry[] = [];

  private timers = new Map<string, ReturnType<typeof setTimeout>>();
  private sequence = 0;

  disconnectedCallback() {
    for (const timer of this.timers.values()) clearTimeout(timer);
    this.timers.clear();
  }

  /**
   * Shows a toast and returns its id.
   *
   * Newest first, matching the React provider, so a stack in a top corner
   * grows downwards away from the corner.
   */
  @Method()
  async toast(options: PfToastOptions = {}): Promise<string> {
    const id = `pf-toast-${(this.sequence += 1)}`;
    this.entries = [{ ...options, id }, ...this.entries];

    const duration = options.duration ?? this.duration;
    if (duration > 0) {
      this.timers.set(
        id,
        setTimeout(() => {
          this.timers.delete(id);
          void this.dismiss(id);
        }, duration),
      );
    }

    return id;
  }

  /** Dismisses one toast by the id `toast()` returned. */
  @Method()
  async dismiss(id: string): Promise<void> {
    this.clearTimer(id);
    /*
     * Typed structurally rather than as `HTMLPfNotificationElement`: that
     * interface is generated by the build, so naming it here makes the first
     * build of a new element fail on the type it is about to produce.
     */
    const element = this.el.shadowRoot?.querySelector(`pf-notification[data-id="${id}"]`) as
      (HTMLElement & { dismiss(): Promise<void> }) | null;

    // Play the exit animation if it is still mounted; remove it either way.
    if (element) await element.dismiss();
    this.remove(id);
  }

  /** Dismisses everything currently showing. */
  @Method()
  async dismissAll(): Promise<void> {
    await Promise.all(this.entries.map((entry) => this.dismiss(entry.id)));
  }

  private clearTimer(id: string) {
    const timer = this.timers.get(id);
    if (timer) clearTimeout(timer);
    this.timers.delete(id);
  }

  private remove(id: string) {
    if (!this.entries.some((entry) => entry.id === id)) return;
    this.entries = this.entries.filter((entry) => entry.id !== id);
    this.pfToastDismiss.emit({ id });
  }

  render() {
    return (
      <Host>
        <div class="stack" part="stack">
          {this.entries.map((entry) => (
            <pf-notification
              key={entry.id}
              data-id={entry.id}
              variant={entry.variant ?? 'info'}
              heading={entry.heading}
              description={entry.description}
              dismissable={entry.dismissable ?? true}
              /*
               * The notification owns its own exit, and tells us when it is
               * over. Removing it on the click instead would cut the animation
               * off at the first frame.
               */
              onPfDismiss={() => this.remove(entry.id)}
            ></pf-notification>
          ))}
          <slot />
        </div>
      </Host>
    );
  }
}
