/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PfAvatarSize, PfAvatarStatus } from "./components/pf-avatar/pf-avatar";
import { PfBadgeVariant } from "./components/pf-badge/pf-badge";
import { PfButtonSize, PfButtonType, PfButtonVariant } from "./components/pf-button/pf-button";
import { PfContentDividerOrientation } from "./components/pf-content-divider/pf-content-divider";
import { PfInputType } from "./components/pf-input/pf-input";
import { PfKbdSize } from "./components/pf-kbd/pf-kbd";
import { PfTagVariant } from "./components/pf-tag/pf-tag";
export { PfAvatarSize, PfAvatarStatus } from "./components/pf-avatar/pf-avatar";
export { PfBadgeVariant } from "./components/pf-badge/pf-badge";
export { PfButtonSize, PfButtonType, PfButtonVariant } from "./components/pf-button/pf-button";
export { PfContentDividerOrientation } from "./components/pf-content-divider/pf-content-divider";
export { PfInputType } from "./components/pf-input/pf-input";
export { PfKbdSize } from "./components/pf-kbd/pf-kbd";
export { PfTagVariant } from "./components/pf-tag/pf-tag";
export namespace Components {
    interface PfAvatar {
        /**
          * Alternative text for the photo.
         */
        "alt"?: string;
        /**
          * The person's name: used for the accessible name and the initials.
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size": PfAvatarSize;
        /**
          * Photo URL. Without one the avatar shows initials.
         */
        "src"?: string;
        /**
          * Presence indicator. Decorative — convey it in text as well.
         */
        "status"?: PfAvatarStatus;
    }
    interface PfBadge {
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant": PfBadgeVariant;
    }
    interface PfButton {
        /**
          * Disable the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Accessible name, for when the slot holds only an icon.
         */
        "label"?: string;
        /**
          * Show a spinner and block interaction.
          * @default false
         */
        "loading": boolean;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size": PfButtonSize;
        /**
          * Mirrors the native attribute. `submit` and `reset` do not yet act on a form outside this element's shadow root -- that needs ElementInternals, which arrives with the form controls in Wave 3.
          * @default 'button'
         */
        "type": PfButtonType;
        /**
          * Visual style. Reflected so the stylesheet can select on it.
          * @default 'primary'
         */
        "variant": PfButtonVariant;
    }
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface PfCard {
    }
    /**
     * The body section of a `pf-card`.
     */
    interface PfCardContent {
    }
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface PfCardFooter {
    }
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface PfCardHeader {
    }
    /**
     * A rule that separates content, optionally labelled.
     */
    interface PfContentDivider {
        /**
          * Pad the divider horizontally. Reflected so the stylesheet can select on it.
          * @default false
         */
        "inset": boolean;
        /**
          * Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation": PfContentDividerOrientation;
    }
    interface PfIcon {
        /**
          * Accessible name. Without one the icon is decorative and hidden from assistive technology, which is the right default beside a text label.
         */
        "label"?: string;
        /**
          * A registered Font Awesome name, one of its aliases, or a custom glyph.
         */
        "name": string;
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface PfInput {
        /**
          * Whether the control currently satisfies its constraints.  A form-associated custom element does not inherit `checkValidity` from anywhere -- the spec puts it on ElementInternals, so the element has to forward it or consumers cannot ask.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.
         */
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": PfInputType;
        /**
          * The control's value.
          * @default ''
         */
        "value": string;
    }
    interface PfKbd {
        /**
          * A key combination rendered as one cap, e.g. `["⌘", "K"]`.
         */
        "keys"?: string[];
        /**
          * Separator between keys in a combination. Defaults to `+`.
          * @default '+'
         */
        "separator": string;
        /**
          * @default 'md'
         */
        "size": PfKbdSize;
    }
    interface PfTag {
        /**
          * Accessible name for the remove button.
          * @default 'Remove tag'
         */
        "dismissLabel": string;
        /**
          * Show a button that removes the tag.
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default 'neutral'
         */
        "variant": PfTagVariant;
    }
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface PfVisuallyHidden {
        /**
          * Reveal the content when it, or a descendant, receives keyboard focus — the classic "skip link" pattern. Reflected so the stylesheet can select on it.
          * @default false
         */
        "focusable": boolean;
    }
}
export interface PfInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfInputElement;
}
export interface PfTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfTagElement;
}
declare global {
    interface HTMLPfAvatarElement extends Components.PfAvatar, HTMLStencilElement {
    }
    var HTMLPfAvatarElement: {
        prototype: HTMLPfAvatarElement;
        new (): HTMLPfAvatarElement;
    };
    interface HTMLPfBadgeElement extends Components.PfBadge, HTMLStencilElement {
    }
    var HTMLPfBadgeElement: {
        prototype: HTMLPfBadgeElement;
        new (): HTMLPfBadgeElement;
    };
    interface HTMLPfButtonElement extends Components.PfButton, HTMLStencilElement {
    }
    var HTMLPfButtonElement: {
        prototype: HTMLPfButtonElement;
        new (): HTMLPfButtonElement;
    };
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface HTMLPfCardElement extends Components.PfCard, HTMLStencilElement {
    }
    var HTMLPfCardElement: {
        prototype: HTMLPfCardElement;
        new (): HTMLPfCardElement;
    };
    /**
     * The body section of a `pf-card`.
     */
    interface HTMLPfCardContentElement extends Components.PfCardContent, HTMLStencilElement {
    }
    var HTMLPfCardContentElement: {
        prototype: HTMLPfCardContentElement;
        new (): HTMLPfCardContentElement;
    };
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface HTMLPfCardFooterElement extends Components.PfCardFooter, HTMLStencilElement {
    }
    var HTMLPfCardFooterElement: {
        prototype: HTMLPfCardFooterElement;
        new (): HTMLPfCardFooterElement;
    };
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface HTMLPfCardHeaderElement extends Components.PfCardHeader, HTMLStencilElement {
    }
    var HTMLPfCardHeaderElement: {
        prototype: HTMLPfCardHeaderElement;
        new (): HTMLPfCardHeaderElement;
    };
    /**
     * A rule that separates content, optionally labelled.
     */
    interface HTMLPfContentDividerElement extends Components.PfContentDivider, HTMLStencilElement {
    }
    var HTMLPfContentDividerElement: {
        prototype: HTMLPfContentDividerElement;
        new (): HTMLPfContentDividerElement;
    };
    interface HTMLPfIconElement extends Components.PfIcon, HTMLStencilElement {
    }
    var HTMLPfIconElement: {
        prototype: HTMLPfIconElement;
        new (): HTMLPfIconElement;
    };
    interface HTMLPfInputElementEventMap {
        "pfInput": { value: string };
        "pfChange": { value: string };
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface HTMLPfInputElement extends Components.PfInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfInputElementEventMap>(type: K, listener: (this: HTMLPfInputElement, ev: PfInputCustomEvent<HTMLPfInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfInputElementEventMap>(type: K, listener: (this: HTMLPfInputElement, ev: PfInputCustomEvent<HTMLPfInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfInputElement: {
        prototype: HTMLPfInputElement;
        new (): HTMLPfInputElement;
    };
    interface HTMLPfKbdElement extends Components.PfKbd, HTMLStencilElement {
    }
    var HTMLPfKbdElement: {
        prototype: HTMLPfKbdElement;
        new (): HTMLPfKbdElement;
    };
    interface HTMLPfTagElementEventMap {
        "pfDismiss": void;
    }
    interface HTMLPfTagElement extends Components.PfTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfTagElementEventMap>(type: K, listener: (this: HTMLPfTagElement, ev: PfTagCustomEvent<HTMLPfTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfTagElementEventMap>(type: K, listener: (this: HTMLPfTagElement, ev: PfTagCustomEvent<HTMLPfTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfTagElement: {
        prototype: HTMLPfTagElement;
        new (): HTMLPfTagElement;
    };
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface HTMLPfVisuallyHiddenElement extends Components.PfVisuallyHidden, HTMLStencilElement {
    }
    var HTMLPfVisuallyHiddenElement: {
        prototype: HTMLPfVisuallyHiddenElement;
        new (): HTMLPfVisuallyHiddenElement;
    };
    interface HTMLElementTagNameMap {
        "pf-avatar": HTMLPfAvatarElement;
        "pf-badge": HTMLPfBadgeElement;
        "pf-button": HTMLPfButtonElement;
        "pf-card": HTMLPfCardElement;
        "pf-card-content": HTMLPfCardContentElement;
        "pf-card-footer": HTMLPfCardFooterElement;
        "pf-card-header": HTMLPfCardHeaderElement;
        "pf-content-divider": HTMLPfContentDividerElement;
        "pf-icon": HTMLPfIconElement;
        "pf-input": HTMLPfInputElement;
        "pf-kbd": HTMLPfKbdElement;
        "pf-tag": HTMLPfTagElement;
        "pf-visually-hidden": HTMLPfVisuallyHiddenElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface PfAvatar {
        /**
          * Alternative text for the photo.
         */
        "alt"?: string;
        /**
          * The person's name: used for the accessible name and the initials.
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: PfAvatarSize;
        /**
          * Photo URL. Without one the avatar shows initials.
         */
        "src"?: string;
        /**
          * Presence indicator. Decorative — convey it in text as well.
         */
        "status"?: PfAvatarStatus;
    }
    interface PfBadge {
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant"?: PfBadgeVariant;
    }
    interface PfButton {
        /**
          * Disable the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Accessible name, for when the slot holds only an icon.
         */
        "label"?: string;
        /**
          * Show a spinner and block interaction.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size"?: PfButtonSize;
        /**
          * Mirrors the native attribute. `submit` and `reset` do not yet act on a form outside this element's shadow root -- that needs ElementInternals, which arrives with the form controls in Wave 3.
          * @default 'button'
         */
        "type"?: PfButtonType;
        /**
          * Visual style. Reflected so the stylesheet can select on it.
          * @default 'primary'
         */
        "variant"?: PfButtonVariant;
    }
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface PfCard {
    }
    /**
     * The body section of a `pf-card`.
     */
    interface PfCardContent {
    }
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface PfCardFooter {
    }
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface PfCardHeader {
    }
    /**
     * A rule that separates content, optionally labelled.
     */
    interface PfContentDivider {
        /**
          * Pad the divider horizontally. Reflected so the stylesheet can select on it.
          * @default false
         */
        "inset"?: boolean;
        /**
          * Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation"?: PfContentDividerOrientation;
    }
    interface PfIcon {
        /**
          * Accessible name. Without one the icon is decorative and hidden from assistive technology, which is the right default beside a text label.
         */
        "label"?: string;
        /**
          * A registered Font Awesome name, one of its aliases, or a custom glyph.
         */
        "name": string;
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface PfInput {
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.
         */
        "name"?: string;
        /**
          * Fires when the value is committed, like the native `change` event.
         */
        "onPfChange"?: (event: PfInputCustomEvent<{ value: string }>) => void;
        /**
          * Fires on every keystroke, like the native `input` event.
         */
        "onPfInput"?: (event: PfInputCustomEvent<{ value: string }>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: PfInputType;
        /**
          * The control's value.
          * @default ''
         */
        "value"?: string;
    }
    interface PfKbd {
        /**
          * A key combination rendered as one cap, e.g. `["⌘", "K"]`.
         */
        "keys"?: string[];
        /**
          * Separator between keys in a combination. Defaults to `+`.
          * @default '+'
         */
        "separator"?: string;
        /**
          * @default 'md'
         */
        "size"?: PfKbdSize;
    }
    interface PfTag {
        /**
          * Accessible name for the remove button.
          * @default 'Remove tag'
         */
        "dismissLabel"?: string;
        /**
          * Show a button that removes the tag.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Fired when the remove button is pressed. The tag does not remove itself — whoever owns the list decides, exactly as the React `onDismiss` callback leaves it to the caller.
         */
        "onPfDismiss"?: (event: PfTagCustomEvent<void>) => void;
        /**
          * @default 'neutral'
         */
        "variant"?: PfTagVariant;
    }
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface PfVisuallyHidden {
        /**
          * Reveal the content when it, or a descendant, receives keyboard focus — the classic "skip link" pattern. Reflected so the stylesheet can select on it.
          * @default false
         */
        "focusable"?: boolean;
    }

    interface PfAvatarAttributes {
        "src": string;
        "alt": string;
        "name": string;
        "size": PfAvatarSize;
        "status": PfAvatarStatus;
    }
    interface PfBadgeAttributes {
        "variant": PfBadgeVariant;
    }
    interface PfButtonAttributes {
        "variant": PfButtonVariant;
        "size": PfButtonSize;
        "fullWidth": boolean;
        "loading": boolean;
        "disabled": boolean;
        "type": PfButtonType;
        "label": string;
    }
    interface PfContentDividerAttributes {
        "orientation": PfContentDividerOrientation;
        "inset": boolean;
    }
    interface PfIconAttributes {
        "name": string;
        "label": string;
    }
    interface PfInputAttributes {
        "name": string;
        "value": string;
        "type": PfInputType;
        "label": string;
        "description": string;
        "error": string;
        "placeholder": string;
        "required": boolean;
        "disabled": boolean;
        "readonly": boolean;
    }
    interface PfKbdAttributes {
        "size": PfKbdSize;
        "separator": string;
    }
    interface PfTagAttributes {
        "variant": PfTagVariant;
        "dismissible": boolean;
        "dismissLabel": string;
    }
    interface PfVisuallyHiddenAttributes {
        "focusable": boolean;
    }

    interface IntrinsicElements {
        "pf-avatar": Omit<PfAvatar, keyof PfAvatarAttributes> & { [K in keyof PfAvatar & keyof PfAvatarAttributes]?: PfAvatar[K] } & { [K in keyof PfAvatar & keyof PfAvatarAttributes as `attr:${K}`]?: PfAvatarAttributes[K] } & { [K in keyof PfAvatar & keyof PfAvatarAttributes as `prop:${K}`]?: PfAvatar[K] };
        "pf-badge": Omit<PfBadge, keyof PfBadgeAttributes> & { [K in keyof PfBadge & keyof PfBadgeAttributes]?: PfBadge[K] } & { [K in keyof PfBadge & keyof PfBadgeAttributes as `attr:${K}`]?: PfBadgeAttributes[K] } & { [K in keyof PfBadge & keyof PfBadgeAttributes as `prop:${K}`]?: PfBadge[K] };
        "pf-button": Omit<PfButton, keyof PfButtonAttributes> & { [K in keyof PfButton & keyof PfButtonAttributes]?: PfButton[K] } & { [K in keyof PfButton & keyof PfButtonAttributes as `attr:${K}`]?: PfButtonAttributes[K] } & { [K in keyof PfButton & keyof PfButtonAttributes as `prop:${K}`]?: PfButton[K] };
        "pf-card": PfCard;
        "pf-card-content": PfCardContent;
        "pf-card-footer": PfCardFooter;
        "pf-card-header": PfCardHeader;
        "pf-content-divider": Omit<PfContentDivider, keyof PfContentDividerAttributes> & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes]?: PfContentDivider[K] } & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes as `attr:${K}`]?: PfContentDividerAttributes[K] } & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes as `prop:${K}`]?: PfContentDivider[K] };
        "pf-icon": Omit<PfIcon, keyof PfIconAttributes> & { [K in keyof PfIcon & keyof PfIconAttributes]?: PfIcon[K] } & { [K in keyof PfIcon & keyof PfIconAttributes as `attr:${K}`]?: PfIconAttributes[K] } & { [K in keyof PfIcon & keyof PfIconAttributes as `prop:${K}`]?: PfIcon[K] } & OneOf<"name", PfIcon["name"], PfIconAttributes["name"]>;
        "pf-input": Omit<PfInput, keyof PfInputAttributes> & { [K in keyof PfInput & keyof PfInputAttributes]?: PfInput[K] } & { [K in keyof PfInput & keyof PfInputAttributes as `attr:${K}`]?: PfInputAttributes[K] } & { [K in keyof PfInput & keyof PfInputAttributes as `prop:${K}`]?: PfInput[K] };
        "pf-kbd": Omit<PfKbd, keyof PfKbdAttributes> & { [K in keyof PfKbd & keyof PfKbdAttributes]?: PfKbd[K] } & { [K in keyof PfKbd & keyof PfKbdAttributes as `attr:${K}`]?: PfKbdAttributes[K] } & { [K in keyof PfKbd & keyof PfKbdAttributes as `prop:${K}`]?: PfKbd[K] };
        "pf-tag": Omit<PfTag, keyof PfTagAttributes> & { [K in keyof PfTag & keyof PfTagAttributes]?: PfTag[K] } & { [K in keyof PfTag & keyof PfTagAttributes as `attr:${K}`]?: PfTagAttributes[K] } & { [K in keyof PfTag & keyof PfTagAttributes as `prop:${K}`]?: PfTag[K] };
        "pf-visually-hidden": Omit<PfVisuallyHidden, keyof PfVisuallyHiddenAttributes> & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes]?: PfVisuallyHidden[K] } & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes as `attr:${K}`]?: PfVisuallyHiddenAttributes[K] } & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes as `prop:${K}`]?: PfVisuallyHidden[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pf-avatar": LocalJSX.IntrinsicElements["pf-avatar"] & JSXBase.HTMLAttributes<HTMLPfAvatarElement>;
            "pf-badge": LocalJSX.IntrinsicElements["pf-badge"] & JSXBase.HTMLAttributes<HTMLPfBadgeElement>;
            "pf-button": LocalJSX.IntrinsicElements["pf-button"] & JSXBase.HTMLAttributes<HTMLPfButtonElement>;
            /**
             * A surface that groups related content.
             * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
             * to four elements rather than to one element with named slots. Named slots
             * would need a slot controller to know whether to render each wrapper at all —
             * an unslotted `header` would otherwise leave a padded, bordered empty strip.
             * Separate elements have no such state: the consumer writing
             * `<pf-card-header>` *is* the signal.
             */
            "pf-card": LocalJSX.IntrinsicElements["pf-card"] & JSXBase.HTMLAttributes<HTMLPfCardElement>;
            /**
             * The body section of a `pf-card`.
             */
            "pf-card-content": LocalJSX.IntrinsicElements["pf-card-content"] & JSXBase.HTMLAttributes<HTMLPfCardContentElement>;
            /**
             * The bottom section of a `pf-card`, separated from what precedes it by a rule.
             * Lays its children out in a row, which is what makes it the natural home for
             * a card's actions.
             */
            "pf-card-footer": LocalJSX.IntrinsicElements["pf-card-footer"] & JSXBase.HTMLAttributes<HTMLPfCardFooterElement>;
            /**
             * The top section of a `pf-card`, separated from what follows by a rule.
             */
            "pf-card-header": LocalJSX.IntrinsicElements["pf-card-header"] & JSXBase.HTMLAttributes<HTMLPfCardHeaderElement>;
            /**
             * A rule that separates content, optionally labelled.
             */
            "pf-content-divider": LocalJSX.IntrinsicElements["pf-content-divider"] & JSXBase.HTMLAttributes<HTMLPfContentDividerElement>;
            "pf-icon": LocalJSX.IntrinsicElements["pf-icon"] & JSXBase.HTMLAttributes<HTMLPfIconElement>;
            /**
             * A form-associated text input.
             * `formAssociated` plus `ElementInternals` is what makes this participate in a
             * real `<form>`: the value reaches `FormData`, constraint validation works, and
             * Angular's generated value accessor has something to bind to. A plain
             * `<input>` inside a shadow root does none of that.
             */
            "pf-input": LocalJSX.IntrinsicElements["pf-input"] & JSXBase.HTMLAttributes<HTMLPfInputElement>;
            "pf-kbd": LocalJSX.IntrinsicElements["pf-kbd"] & JSXBase.HTMLAttributes<HTMLPfKbdElement>;
            "pf-tag": LocalJSX.IntrinsicElements["pf-tag"] & JSXBase.HTMLAttributes<HTMLPfTagElement>;
            /**
             * Hides content visually while keeping it available to screen readers and
             * other assistive technology. Use for labels, instructions and status text
             * that are implied visually but need to be announced.
             * The React component takes an `as` prop to choose its tag; a custom element's
             * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
             * hidden>Results</pf-visually-hidden></h2>` is still a heading named
             * "Results".
             */
            "pf-visually-hidden": LocalJSX.IntrinsicElements["pf-visually-hidden"] & JSXBase.HTMLAttributes<HTMLPfVisuallyHiddenElement>;
        }
    }
}
