/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PfAvatarSize, PfAvatarStatus } from "./components/pf-avatar/pf-avatar";
import { PfBadgeVariant } from "./components/pf-badge/pf-badge";
import { PfBadgeGroupAppearance, PfBadgeGroupBadgePosition, PfBadgeGroupColor } from "./components/pf-badge-group/pf-badge-group";
import { PfButtonSize, PfButtonType, PfButtonVariant } from "./components/pf-button/pf-button";
import { PfContentDividerOrientation } from "./components/pf-content-divider/pf-content-divider";
import { PfCreditCardBrand } from "./components/pf-credit-card/pf-credit-card";
import { PfInputType } from "./components/pf-input/pf-input";
import { PfKbdSize } from "./components/pf-kbd/pf-kbd";
import { PfLoadingDotsSize } from "./components/pf-loading-dots/pf-loading-dots";
import { PfScrollAreaOrientation } from "./components/pf-scroll-area/pf-scroll-area";
import { PfTagVariant } from "./components/pf-tag/pf-tag";
import { PfToolbarOrientation } from "./components/pf-toolbar/pf-toolbar";
import { PfToolbarSeparatorOrientation } from "./components/pf-toolbar-separator/pf-toolbar-separator";
import { PfUtilityButtonSize, PfUtilityButtonVariant } from "./components/pf-utility-button/pf-utility-button";
export { PfAvatarSize, PfAvatarStatus } from "./components/pf-avatar/pf-avatar";
export { PfBadgeVariant } from "./components/pf-badge/pf-badge";
export { PfBadgeGroupAppearance, PfBadgeGroupBadgePosition, PfBadgeGroupColor } from "./components/pf-badge-group/pf-badge-group";
export { PfButtonSize, PfButtonType, PfButtonVariant } from "./components/pf-button/pf-button";
export { PfContentDividerOrientation } from "./components/pf-content-divider/pf-content-divider";
export { PfCreditCardBrand } from "./components/pf-credit-card/pf-credit-card";
export { PfInputType } from "./components/pf-input/pf-input";
export { PfKbdSize } from "./components/pf-kbd/pf-kbd";
export { PfLoadingDotsSize } from "./components/pf-loading-dots/pf-loading-dots";
export { PfScrollAreaOrientation } from "./components/pf-scroll-area/pf-scroll-area";
export { PfTagVariant } from "./components/pf-tag/pf-tag";
export { PfToolbarOrientation } from "./components/pf-toolbar/pf-toolbar";
export { PfToolbarSeparatorOrientation } from "./components/pf-toolbar-separator/pf-toolbar-separator";
export { PfUtilityButtonSize, PfUtilityButtonVariant } from "./components/pf-utility-button/pf-utility-button";
export namespace Components {
    interface PfAvatar {
        /**
          * Alternative text for the photo.
         */
        "alt"?: string;
        /**
          * The person's name: used for the accessible name and the initials.
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size": PfAvatarSize;
        /**
          * Photo URL. Without one the avatar shows initials.
         */
        "src"?: string;
        /**
          * Presence indicator. Decorative — convey it in text as well.
         */
        "status"?: PfAvatarStatus;
    }
    interface PfBadge {
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant": PfBadgeVariant;
    }
    /**
     * A badge joined to a line of text, sharing one rounded outline — the
     * "2 new · See what's changed" pattern.
     */
    interface PfBadgeGroup {
        /**
          * Surface treatment for the message. Reflected for the stylesheet.
          * @default 'pill'
         */
        "appearance": PfBadgeGroupAppearance;
        /**
          * Which side the badge sits on. Reflected for the stylesheet.
          * @default 'leading'
         */
        "badgePosition": PfBadgeGroupBadgePosition;
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'gray'
         */
        "color": PfBadgeGroupColor;
        /**
          * The badge's text.
          * @default ''
         */
        "label": string;
        /**
          * The message beside the badge.
          * @default ''
         */
        "message": string;
    }
    interface PfButton {
        /**
          * Disable the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Accessible name, for when the slot holds only an icon.
         */
        "label"?: string;
        /**
          * Show a spinner and block interaction.
          * @default false
         */
        "loading": boolean;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size": PfButtonSize;
        /**
          * Mirrors the native attribute. `submit` and `reset` do not yet act on a form outside this element's shadow root -- that needs ElementInternals, which arrives with the form controls in Wave 3.
          * @default 'button'
         */
        "type": PfButtonType;
        /**
          * Visual style. Reflected so the stylesheet can select on it.
          * @default 'primary'
         */
        "variant": PfButtonVariant;
    }
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface PfCard {
    }
    /**
     * The body section of a `pf-card`.
     */
    interface PfCardContent {
    }
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface PfCardFooter {
    }
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface PfCardHeader {
    }
    /**
     * A form-associated checkbox.
     */
    interface PfCheckbox {
        /**
          * A form-associated custom element does not inherit this.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Whether the box is ticked. Reflected so the stylesheet can select on it.
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * What is submitted when ticked. Mirrors the native attribute, whose default is also `on` — a checkbox with no value still submits something.
          * @default 'on'
         */
        "value": string;
    }
    /**
     * A rule that separates content, optionally labelled.
     */
    interface PfContentDivider {
        /**
          * Pad the divider horizontally. Reflected so the stylesheet can select on it.
          * @default false
         */
        "inset": boolean;
        /**
          * Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation": PfContentDividerOrientation;
    }
    /**
     * A card-shaped display of payment details. Presentational only — it stores
     * nothing and submits nothing.
     */
    interface PfCreditCard {
        /**
          * Card network. Reflected so the stylesheet can pick the gradient.
          * @default 'generic'
         */
        "brand": PfCreditCardBrand;
        /**
          * The number to display. Separators in the input are regrouped.
          * @default ''
         */
        "cardNumber": string;
        /**
          * Name on the card.
          * @default ''
         */
        "cardholderName": string;
        /**
          * Security code. Omit it to leave the field out entirely.
         */
        "cvc"?: string;
        /**
          * Expiry, displayed as given.
          * @default ''
         */
        "expiry": string;
        /**
          * Hide all but the last four digits, and the CVC with it. Defaults to true, so the careless case is the safe one. Reflected for the stylesheet.
          * @default true
         */
        "masked": boolean;
    }
    interface PfIcon {
        /**
          * Accessible name. Without one the icon is decorative and hidden from assistive technology, which is the right default beside a text label.
         */
        "label"?: string;
        /**
          * A registered Font Awesome name, one of its aliases, or a custom glyph.
         */
        "name": string;
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface PfInput {
        /**
          * Whether the control currently satisfies its constraints.  A form-associated custom element does not inherit `checkValidity` from anywhere -- the spec puts it on ElementInternals, so the element has to forward it or consumers cannot ask.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": PfInputType;
        /**
          * The control's value.
          * @default ''
         */
        "value": string;
    }
    interface PfKbd {
        /**
          * A key combination rendered as one cap, e.g. `["⌘", "K"]`.
         */
        "keys"?: string[];
        /**
          * Separator between keys in a combination. Defaults to `+`.
          * @default '+'
         */
        "separator": string;
        /**
          * @default 'md'
         */
        "size": PfKbdSize;
    }
    /**
     * Three pulsing dots, for an indeterminate wait in a tight space.
     */
    interface PfLoadingDots {
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading'
         */
        "label": string;
        /**
          * Dot size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size": PfLoadingDotsSize;
    }
    /**
     * A shimmering placeholder for content that has not arrived.
     */
    interface PfLoadingSkeleton {
        /**
          * Height, as a CSS length. A bare number is read as pixels.
          * @default 16
         */
        "height": number | string;
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading content'
         */
        "label": string;
        /**
          * Use a pill radius instead of the default. Reflected for the stylesheet.
          * @default false
         */
        "rounded": boolean;
        /**
          * Width, as a CSS length. A bare number is read as pixels.
          * @default '100%'
         */
        "width": number | string;
    }
    /**
     * An indeterminate spinner.
     */
    interface PfLoadingSpinner {
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading'
         */
        "label": string;
        /**
          * Diameter in pixels.
          * @default 24
         */
        "size": number;
    }
    /**
     * A pager: boundary pages pinned at each end, a window around the current
     * page, and an ellipsis wherever that leaves a gap.
     * Controlled or not, like `pf-input`: `page` is mutable, so leaving it alone
     * lets the element advance itself, and setting it on every `pfPageChange`
     * keeps the consumer in charge.
     */
    interface PfPagination {
        /**
          * Pages to pin at each end.
          * @default 1
         */
        "boundaryCount": number;
        /**
          * Disable every button. Reflected for the stylesheet.
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible name for the navigation landmark.
          * @default 'Pagination'
         */
        "label": string;
        /**
          * The current page, 1-based. Mutable so the element can advance itself.
          * @default 1
         */
        "page": number;
        /**
          * Show the previous/next buttons. Reflected for the stylesheet.
          * @default true
         */
        "showPrevNext": boolean;
        /**
          * Pages to show either side of the current one.
          * @default 1
         */
        "siblingCount": number;
        /**
          * How many pages there are in total.
          * @default 1
         */
        "totalPages": number;
    }
    /**
     * A horizontal determinate progress track.
     */
    interface PfProgressBar {
        /**
          * Accessible name.
         */
        "label"?: string;
        /**
          * The top of the scale.
          * @default 100
         */
        "max": number;
        /**
          * Show the percentage beside the track. Reflected for the stylesheet.
          * @default true
         */
        "showValue": boolean;
        /**
          * How far along, on the 0..max scale.
          * @default 0
         */
        "value": number;
    }
    /**
     * A circular determinate progress track.
     */
    interface PfProgressCircle {
        /**
          * Accessible name.
         */
        "label"?: string;
        /**
          * The top of the scale.
          * @default 100
         */
        "max": number;
        /**
          * Show the percentage in the middle. Reflected for the stylesheet.
          * @default true
         */
        "showValue": boolean;
        /**
          * Diameter in pixels.
          * @default 64
         */
        "size": number;
        /**
          * Ring thickness in pixels.
          * @default 6
         */
        "strokeWidth": number;
        /**
          * How far along, on the 0..max scale.
          * @default 0
         */
        "value": number;
    }
    /**
     * A scrollable region with a styled, non-overlaying scrollbar.
     */
    interface PfScrollArea {
        /**
          * Make the region keyboard-focusable so it can be scrolled with the arrow keys (WCAG 2.1.1). Set false when a focusable child already provides keyboard access.
          * @default true
         */
        "focusable": boolean;
        /**
          * Which axis scrolls. Reflected so the stylesheet can select on it.
          * @default 'vertical'
         */
        "orientation": PfScrollAreaOrientation;
    }
    /**
     * A form-associated range slider.
     * A native `<input type="range">`, as the React component is — the drag, the
     * keyboard stepping and the touch handling are all the browser's, and nothing
     * here reimplements them.
     */
    interface PfSlider {
        /**
          * A form-associated custom element does not inherit this.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * Submitted under this name. Reflected, because a form-associated element takes its submission name from the attribute, not this property.
         */
        "name"?: string;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Show the current value beside the label. Reflected for the stylesheet.
          * @default true
         */
        "showValue": boolean;
        /**
          * @default 1
         */
        "step": number;
        /**
          * The control's value.
          * @default 0
         */
        "value": number;
    }
    /**
     * A form-associated on/off switch.
     * Built on a native checkbox with `role="switch"`, exactly as the React
     * component is: a switch is a checkbox whose two states are "on" and "off"
     * rather than "selected" and "not selected", and the role is the only
     * difference assistive technology needs.
     */
    interface PfSwitch {
        /**
          * A form-associated custom element does not inherit this.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Whether the switch is on. Reflected so the stylesheet can select on it.
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * What is submitted when on. Mirrors the native attribute, whose default is also `on` — a checkbox with no value still submits something.
          * @default 'on'
         */
        "value": string;
    }
    interface PfTag {
        /**
          * Accessible name for the remove button.
          * @default 'Remove tag'
         */
        "dismissLabel": string;
        /**
          * Show a button that removes the tag.
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default 'neutral'
         */
        "variant": PfTagVariant;
    }
    /**
     * A form-associated multi-line text control.
     * Shares `pf-input`'s field anatomy and form wiring; the control is a
     * `<textarea>` rather than an `<input>`, so it takes `rows` and resizes.
     */
    interface PfTextarea {
        /**
          * Whether the control currently satisfies its constraints.  A form-associated custom element does not inherit `checkValidity` from anywhere -- the spec puts it on ElementInternals, so the element has to forward it or consumers cannot ask.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The message explaining why the control is invalid, or an empty string.
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * As `checkValidity`, but also shows the browser's validation message.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * Visible rows. Mirrors the native attribute.
          * @default 4
         */
        "rows": number;
        /**
          * The control's value.
          * @default ''
         */
        "value": string;
    }
    /**
     * A group of controls that is one tab stop from outside and navigated
     * internally with the arrow keys.
     * Items are matched in the light DOM, so a native `button`, `a[href]` or form
     * control works with no ceremony. A custom element is not a native control and
     * has to opt in with `data-toolbar-item` — `<pf-button data-toolbar-item>`.
     * Focusing it still reaches the real button inside, because `pf-button`
     * delegates focus.
     */
    interface PfToolbar {
        /**
          * Layout and arrow-key axis. Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation": PfToolbarOrientation;
    }
    /**
     * A rule between groups of toolbar controls.
     * `orientation` describes the toolbar it sits in, not the rule's own shape: a
     * horizontal toolbar gets a vertical hairline. `pf-toolbar` sets it on every
     * separator it contains, so a consumer does not have to — and cannot leave one
     * pointing the wrong way.
     */
    interface PfToolbarSeparator {
        /**
          * The axis of the toolbar this sits in. Reflected for the stylesheet.
          * @default 'horizontal'
         */
        "orientation": PfToolbarSeparatorOrientation;
    }
    /**
     * A compact button for toolbars and table rows, where the affordance is often
     * an icon alone.
     */
    interface PfUtilityButton {
        /**
          * Disable the button. Reflected so the stylesheet can select on it.
          * @default false
         */
        "disabled": boolean;
        /**
          * Accessible name. Required for an icon-only button, and also used as the native tooltip unless `tooltip` says otherwise.
         */
        "label"?: string;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size": PfUtilityButtonSize;
        /**
          * Native tooltip text. Defaults to `label`.
         */
        "tooltip"?: string;
        /**
          * Mirrors the native attribute.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant": PfUtilityButtonVariant;
    }
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface PfVisuallyHidden {
        /**
          * Reveal the content when it, or a descendant, receives keyboard focus — the classic "skip link" pattern. Reflected so the stylesheet can select on it.
          * @default false
         */
        "focusable": boolean;
    }
}
export interface PfCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfCheckboxElement;
}
export interface PfInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfInputElement;
}
export interface PfPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfPaginationElement;
}
export interface PfSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfSliderElement;
}
export interface PfSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfSwitchElement;
}
export interface PfTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfTagElement;
}
export interface PfTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPfTextareaElement;
}
declare global {
    interface HTMLPfAvatarElement extends Components.PfAvatar, HTMLStencilElement {
    }
    var HTMLPfAvatarElement: {
        prototype: HTMLPfAvatarElement;
        new (): HTMLPfAvatarElement;
    };
    interface HTMLPfBadgeElement extends Components.PfBadge, HTMLStencilElement {
    }
    var HTMLPfBadgeElement: {
        prototype: HTMLPfBadgeElement;
        new (): HTMLPfBadgeElement;
    };
    /**
     * A badge joined to a line of text, sharing one rounded outline — the
     * "2 new · See what's changed" pattern.
     */
    interface HTMLPfBadgeGroupElement extends Components.PfBadgeGroup, HTMLStencilElement {
    }
    var HTMLPfBadgeGroupElement: {
        prototype: HTMLPfBadgeGroupElement;
        new (): HTMLPfBadgeGroupElement;
    };
    interface HTMLPfButtonElement extends Components.PfButton, HTMLStencilElement {
    }
    var HTMLPfButtonElement: {
        prototype: HTMLPfButtonElement;
        new (): HTMLPfButtonElement;
    };
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface HTMLPfCardElement extends Components.PfCard, HTMLStencilElement {
    }
    var HTMLPfCardElement: {
        prototype: HTMLPfCardElement;
        new (): HTMLPfCardElement;
    };
    /**
     * The body section of a `pf-card`.
     */
    interface HTMLPfCardContentElement extends Components.PfCardContent, HTMLStencilElement {
    }
    var HTMLPfCardContentElement: {
        prototype: HTMLPfCardContentElement;
        new (): HTMLPfCardContentElement;
    };
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface HTMLPfCardFooterElement extends Components.PfCardFooter, HTMLStencilElement {
    }
    var HTMLPfCardFooterElement: {
        prototype: HTMLPfCardFooterElement;
        new (): HTMLPfCardFooterElement;
    };
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface HTMLPfCardHeaderElement extends Components.PfCardHeader, HTMLStencilElement {
    }
    var HTMLPfCardHeaderElement: {
        prototype: HTMLPfCardHeaderElement;
        new (): HTMLPfCardHeaderElement;
    };
    interface HTMLPfCheckboxElementEventMap {
        "pfChange": { checked: boolean; value: string };
    }
    /**
     * A form-associated checkbox.
     */
    interface HTMLPfCheckboxElement extends Components.PfCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfCheckboxElementEventMap>(type: K, listener: (this: HTMLPfCheckboxElement, ev: PfCheckboxCustomEvent<HTMLPfCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfCheckboxElementEventMap>(type: K, listener: (this: HTMLPfCheckboxElement, ev: PfCheckboxCustomEvent<HTMLPfCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfCheckboxElement: {
        prototype: HTMLPfCheckboxElement;
        new (): HTMLPfCheckboxElement;
    };
    /**
     * A rule that separates content, optionally labelled.
     */
    interface HTMLPfContentDividerElement extends Components.PfContentDivider, HTMLStencilElement {
    }
    var HTMLPfContentDividerElement: {
        prototype: HTMLPfContentDividerElement;
        new (): HTMLPfContentDividerElement;
    };
    /**
     * A card-shaped display of payment details. Presentational only — it stores
     * nothing and submits nothing.
     */
    interface HTMLPfCreditCardElement extends Components.PfCreditCard, HTMLStencilElement {
    }
    var HTMLPfCreditCardElement: {
        prototype: HTMLPfCreditCardElement;
        new (): HTMLPfCreditCardElement;
    };
    interface HTMLPfIconElement extends Components.PfIcon, HTMLStencilElement {
    }
    var HTMLPfIconElement: {
        prototype: HTMLPfIconElement;
        new (): HTMLPfIconElement;
    };
    interface HTMLPfInputElementEventMap {
        "pfInput": { value: string };
        "pfChange": { value: string };
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface HTMLPfInputElement extends Components.PfInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfInputElementEventMap>(type: K, listener: (this: HTMLPfInputElement, ev: PfInputCustomEvent<HTMLPfInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfInputElementEventMap>(type: K, listener: (this: HTMLPfInputElement, ev: PfInputCustomEvent<HTMLPfInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfInputElement: {
        prototype: HTMLPfInputElement;
        new (): HTMLPfInputElement;
    };
    interface HTMLPfKbdElement extends Components.PfKbd, HTMLStencilElement {
    }
    var HTMLPfKbdElement: {
        prototype: HTMLPfKbdElement;
        new (): HTMLPfKbdElement;
    };
    /**
     * Three pulsing dots, for an indeterminate wait in a tight space.
     */
    interface HTMLPfLoadingDotsElement extends Components.PfLoadingDots, HTMLStencilElement {
    }
    var HTMLPfLoadingDotsElement: {
        prototype: HTMLPfLoadingDotsElement;
        new (): HTMLPfLoadingDotsElement;
    };
    /**
     * A shimmering placeholder for content that has not arrived.
     */
    interface HTMLPfLoadingSkeletonElement extends Components.PfLoadingSkeleton, HTMLStencilElement {
    }
    var HTMLPfLoadingSkeletonElement: {
        prototype: HTMLPfLoadingSkeletonElement;
        new (): HTMLPfLoadingSkeletonElement;
    };
    /**
     * An indeterminate spinner.
     */
    interface HTMLPfLoadingSpinnerElement extends Components.PfLoadingSpinner, HTMLStencilElement {
    }
    var HTMLPfLoadingSpinnerElement: {
        prototype: HTMLPfLoadingSpinnerElement;
        new (): HTMLPfLoadingSpinnerElement;
    };
    interface HTMLPfPaginationElementEventMap {
        "pfPageChange": { page: number };
    }
    /**
     * A pager: boundary pages pinned at each end, a window around the current
     * page, and an ellipsis wherever that leaves a gap.
     * Controlled or not, like `pf-input`: `page` is mutable, so leaving it alone
     * lets the element advance itself, and setting it on every `pfPageChange`
     * keeps the consumer in charge.
     */
    interface HTMLPfPaginationElement extends Components.PfPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfPaginationElementEventMap>(type: K, listener: (this: HTMLPfPaginationElement, ev: PfPaginationCustomEvent<HTMLPfPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfPaginationElementEventMap>(type: K, listener: (this: HTMLPfPaginationElement, ev: PfPaginationCustomEvent<HTMLPfPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfPaginationElement: {
        prototype: HTMLPfPaginationElement;
        new (): HTMLPfPaginationElement;
    };
    /**
     * A horizontal determinate progress track.
     */
    interface HTMLPfProgressBarElement extends Components.PfProgressBar, HTMLStencilElement {
    }
    var HTMLPfProgressBarElement: {
        prototype: HTMLPfProgressBarElement;
        new (): HTMLPfProgressBarElement;
    };
    /**
     * A circular determinate progress track.
     */
    interface HTMLPfProgressCircleElement extends Components.PfProgressCircle, HTMLStencilElement {
    }
    var HTMLPfProgressCircleElement: {
        prototype: HTMLPfProgressCircleElement;
        new (): HTMLPfProgressCircleElement;
    };
    /**
     * A scrollable region with a styled, non-overlaying scrollbar.
     */
    interface HTMLPfScrollAreaElement extends Components.PfScrollArea, HTMLStencilElement {
    }
    var HTMLPfScrollAreaElement: {
        prototype: HTMLPfScrollAreaElement;
        new (): HTMLPfScrollAreaElement;
    };
    interface HTMLPfSliderElementEventMap {
        "pfInput": { value: number };
        "pfChange": { value: number };
    }
    /**
     * A form-associated range slider.
     * A native `<input type="range">`, as the React component is — the drag, the
     * keyboard stepping and the touch handling are all the browser's, and nothing
     * here reimplements them.
     */
    interface HTMLPfSliderElement extends Components.PfSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfSliderElementEventMap>(type: K, listener: (this: HTMLPfSliderElement, ev: PfSliderCustomEvent<HTMLPfSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfSliderElementEventMap>(type: K, listener: (this: HTMLPfSliderElement, ev: PfSliderCustomEvent<HTMLPfSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfSliderElement: {
        prototype: HTMLPfSliderElement;
        new (): HTMLPfSliderElement;
    };
    interface HTMLPfSwitchElementEventMap {
        "pfChange": { checked: boolean; value: string };
    }
    /**
     * A form-associated on/off switch.
     * Built on a native checkbox with `role="switch"`, exactly as the React
     * component is: a switch is a checkbox whose two states are "on" and "off"
     * rather than "selected" and "not selected", and the role is the only
     * difference assistive technology needs.
     */
    interface HTMLPfSwitchElement extends Components.PfSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfSwitchElementEventMap>(type: K, listener: (this: HTMLPfSwitchElement, ev: PfSwitchCustomEvent<HTMLPfSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfSwitchElementEventMap>(type: K, listener: (this: HTMLPfSwitchElement, ev: PfSwitchCustomEvent<HTMLPfSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfSwitchElement: {
        prototype: HTMLPfSwitchElement;
        new (): HTMLPfSwitchElement;
    };
    interface HTMLPfTagElementEventMap {
        "pfDismiss": void;
    }
    interface HTMLPfTagElement extends Components.PfTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfTagElementEventMap>(type: K, listener: (this: HTMLPfTagElement, ev: PfTagCustomEvent<HTMLPfTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfTagElementEventMap>(type: K, listener: (this: HTMLPfTagElement, ev: PfTagCustomEvent<HTMLPfTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfTagElement: {
        prototype: HTMLPfTagElement;
        new (): HTMLPfTagElement;
    };
    interface HTMLPfTextareaElementEventMap {
        "pfInput": { value: string };
        "pfChange": { value: string };
    }
    /**
     * A form-associated multi-line text control.
     * Shares `pf-input`'s field anatomy and form wiring; the control is a
     * `<textarea>` rather than an `<input>`, so it takes `rows` and resizes.
     */
    interface HTMLPfTextareaElement extends Components.PfTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPfTextareaElementEventMap>(type: K, listener: (this: HTMLPfTextareaElement, ev: PfTextareaCustomEvent<HTMLPfTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPfTextareaElementEventMap>(type: K, listener: (this: HTMLPfTextareaElement, ev: PfTextareaCustomEvent<HTMLPfTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPfTextareaElement: {
        prototype: HTMLPfTextareaElement;
        new (): HTMLPfTextareaElement;
    };
    /**
     * A group of controls that is one tab stop from outside and navigated
     * internally with the arrow keys.
     * Items are matched in the light DOM, so a native `button`, `a[href]` or form
     * control works with no ceremony. A custom element is not a native control and
     * has to opt in with `data-toolbar-item` — `<pf-button data-toolbar-item>`.
     * Focusing it still reaches the real button inside, because `pf-button`
     * delegates focus.
     */
    interface HTMLPfToolbarElement extends Components.PfToolbar, HTMLStencilElement {
    }
    var HTMLPfToolbarElement: {
        prototype: HTMLPfToolbarElement;
        new (): HTMLPfToolbarElement;
    };
    /**
     * A rule between groups of toolbar controls.
     * `orientation` describes the toolbar it sits in, not the rule's own shape: a
     * horizontal toolbar gets a vertical hairline. `pf-toolbar` sets it on every
     * separator it contains, so a consumer does not have to — and cannot leave one
     * pointing the wrong way.
     */
    interface HTMLPfToolbarSeparatorElement extends Components.PfToolbarSeparator, HTMLStencilElement {
    }
    var HTMLPfToolbarSeparatorElement: {
        prototype: HTMLPfToolbarSeparatorElement;
        new (): HTMLPfToolbarSeparatorElement;
    };
    /**
     * A compact button for toolbars and table rows, where the affordance is often
     * an icon alone.
     */
    interface HTMLPfUtilityButtonElement extends Components.PfUtilityButton, HTMLStencilElement {
    }
    var HTMLPfUtilityButtonElement: {
        prototype: HTMLPfUtilityButtonElement;
        new (): HTMLPfUtilityButtonElement;
    };
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface HTMLPfVisuallyHiddenElement extends Components.PfVisuallyHidden, HTMLStencilElement {
    }
    var HTMLPfVisuallyHiddenElement: {
        prototype: HTMLPfVisuallyHiddenElement;
        new (): HTMLPfVisuallyHiddenElement;
    };
    interface HTMLElementTagNameMap {
        "pf-avatar": HTMLPfAvatarElement;
        "pf-badge": HTMLPfBadgeElement;
        "pf-badge-group": HTMLPfBadgeGroupElement;
        "pf-button": HTMLPfButtonElement;
        "pf-card": HTMLPfCardElement;
        "pf-card-content": HTMLPfCardContentElement;
        "pf-card-footer": HTMLPfCardFooterElement;
        "pf-card-header": HTMLPfCardHeaderElement;
        "pf-checkbox": HTMLPfCheckboxElement;
        "pf-content-divider": HTMLPfContentDividerElement;
        "pf-credit-card": HTMLPfCreditCardElement;
        "pf-icon": HTMLPfIconElement;
        "pf-input": HTMLPfInputElement;
        "pf-kbd": HTMLPfKbdElement;
        "pf-loading-dots": HTMLPfLoadingDotsElement;
        "pf-loading-skeleton": HTMLPfLoadingSkeletonElement;
        "pf-loading-spinner": HTMLPfLoadingSpinnerElement;
        "pf-pagination": HTMLPfPaginationElement;
        "pf-progress-bar": HTMLPfProgressBarElement;
        "pf-progress-circle": HTMLPfProgressCircleElement;
        "pf-scroll-area": HTMLPfScrollAreaElement;
        "pf-slider": HTMLPfSliderElement;
        "pf-switch": HTMLPfSwitchElement;
        "pf-tag": HTMLPfTagElement;
        "pf-textarea": HTMLPfTextareaElement;
        "pf-toolbar": HTMLPfToolbarElement;
        "pf-toolbar-separator": HTMLPfToolbarSeparatorElement;
        "pf-utility-button": HTMLPfUtilityButtonElement;
        "pf-visually-hidden": HTMLPfVisuallyHiddenElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface PfAvatar {
        /**
          * Alternative text for the photo.
         */
        "alt"?: string;
        /**
          * The person's name: used for the accessible name and the initials.
         */
        "name"?: string;
        /**
          * @default 'md'
         */
        "size"?: PfAvatarSize;
        /**
          * Photo URL. Without one the avatar shows initials.
         */
        "src"?: string;
        /**
          * Presence indicator. Decorative — convey it in text as well.
         */
        "status"?: PfAvatarStatus;
    }
    interface PfBadge {
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant"?: PfBadgeVariant;
    }
    /**
     * A badge joined to a line of text, sharing one rounded outline — the
     * "2 new · See what's changed" pattern.
     */
    interface PfBadgeGroup {
        /**
          * Surface treatment for the message. Reflected for the stylesheet.
          * @default 'pill'
         */
        "appearance"?: PfBadgeGroupAppearance;
        /**
          * Which side the badge sits on. Reflected for the stylesheet.
          * @default 'leading'
         */
        "badgePosition"?: PfBadgeGroupBadgePosition;
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'gray'
         */
        "color"?: PfBadgeGroupColor;
        /**
          * The badge's text.
          * @default ''
         */
        "label"?: string;
        /**
          * The message beside the badge.
          * @default ''
         */
        "message"?: string;
    }
    interface PfButton {
        /**
          * Disable the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretch to the width of the container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Accessible name, for when the slot holds only an icon.
         */
        "label"?: string;
        /**
          * Show a spinner and block interaction.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size"?: PfButtonSize;
        /**
          * Mirrors the native attribute. `submit` and `reset` do not yet act on a form outside this element's shadow root -- that needs ElementInternals, which arrives with the form controls in Wave 3.
          * @default 'button'
         */
        "type"?: PfButtonType;
        /**
          * Visual style. Reflected so the stylesheet can select on it.
          * @default 'primary'
         */
        "variant"?: PfButtonVariant;
    }
    /**
     * A surface that groups related content.
     * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
     * to four elements rather than to one element with named slots. Named slots
     * would need a slot controller to know whether to render each wrapper at all —
     * an unslotted `header` would otherwise leave a padded, bordered empty strip.
     * Separate elements have no such state: the consumer writing
     * `<pf-card-header>` *is* the signal.
     */
    interface PfCard {
    }
    /**
     * The body section of a `pf-card`.
     */
    interface PfCardContent {
    }
    /**
     * The bottom section of a `pf-card`, separated from what precedes it by a rule.
     * Lays its children out in a row, which is what makes it the natural home for
     * a card's actions.
     */
    interface PfCardFooter {
    }
    /**
     * The top section of a `pf-card`, separated from what follows by a rule.
     */
    interface PfCardHeader {
    }
    /**
     * A form-associated checkbox.
     */
    interface PfCheckbox {
        /**
          * Whether the box is ticked. Reflected so the stylesheet can select on it.
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * Fires when the user ticks or unticks the box.
         */
        "onPfChange"?: (event: PfCheckboxCustomEvent<{ checked: boolean; value: string }>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * What is submitted when ticked. Mirrors the native attribute, whose default is also `on` — a checkbox with no value still submits something.
          * @default 'on'
         */
        "value"?: string;
    }
    /**
     * A rule that separates content, optionally labelled.
     */
    interface PfContentDivider {
        /**
          * Pad the divider horizontally. Reflected so the stylesheet can select on it.
          * @default false
         */
        "inset"?: boolean;
        /**
          * Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation"?: PfContentDividerOrientation;
    }
    /**
     * A card-shaped display of payment details. Presentational only — it stores
     * nothing and submits nothing.
     */
    interface PfCreditCard {
        /**
          * Card network. Reflected so the stylesheet can pick the gradient.
          * @default 'generic'
         */
        "brand"?: PfCreditCardBrand;
        /**
          * The number to display. Separators in the input are regrouped.
          * @default ''
         */
        "cardNumber"?: string;
        /**
          * Name on the card.
          * @default ''
         */
        "cardholderName"?: string;
        /**
          * Security code. Omit it to leave the field out entirely.
         */
        "cvc"?: string;
        /**
          * Expiry, displayed as given.
          * @default ''
         */
        "expiry"?: string;
        /**
          * Hide all but the last four digits, and the CVC with it. Defaults to true, so the careless case is the safe one. Reflected for the stylesheet.
          * @default true
         */
        "masked"?: boolean;
    }
    interface PfIcon {
        /**
          * Accessible name. Without one the icon is decorative and hidden from assistive technology, which is the right default beside a text label.
         */
        "label"?: string;
        /**
          * A registered Font Awesome name, one of its aliases, or a custom glyph.
         */
        "name": string;
    }
    /**
     * A form-associated text input.
     * `formAssociated` plus `ElementInternals` is what makes this participate in a
     * real `<form>`: the value reaches `FormData`, constraint validation works, and
     * Angular's generated value accessor has something to bind to. A plain
     * `<input>` inside a shadow root does none of that.
     */
    interface PfInput {
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * Fires when the value is committed, like the native `change` event.
         */
        "onPfChange"?: (event: PfInputCustomEvent<{ value: string }>) => void;
        /**
          * Fires on every keystroke, like the native `input` event.
         */
        "onPfInput"?: (event: PfInputCustomEvent<{ value: string }>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: PfInputType;
        /**
          * The control's value.
          * @default ''
         */
        "value"?: string;
    }
    interface PfKbd {
        /**
          * A key combination rendered as one cap, e.g. `["⌘", "K"]`.
         */
        "keys"?: string[];
        /**
          * Separator between keys in a combination. Defaults to `+`.
          * @default '+'
         */
        "separator"?: string;
        /**
          * @default 'md'
         */
        "size"?: PfKbdSize;
    }
    /**
     * Three pulsing dots, for an indeterminate wait in a tight space.
     */
    interface PfLoadingDots {
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading'
         */
        "label"?: string;
        /**
          * Dot size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size"?: PfLoadingDotsSize;
    }
    /**
     * A shimmering placeholder for content that has not arrived.
     */
    interface PfLoadingSkeleton {
        /**
          * Height, as a CSS length. A bare number is read as pixels.
          * @default 16
         */
        "height"?: number | string;
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading content'
         */
        "label"?: string;
        /**
          * Use a pill radius instead of the default. Reflected for the stylesheet.
          * @default false
         */
        "rounded"?: boolean;
        /**
          * Width, as a CSS length. A bare number is read as pixels.
          * @default '100%'
         */
        "width"?: number | string;
    }
    /**
     * An indeterminate spinner.
     */
    interface PfLoadingSpinner {
        /**
          * Accessible name, announced by the live region.
          * @default 'Loading'
         */
        "label"?: string;
        /**
          * Diameter in pixels.
          * @default 24
         */
        "size"?: number;
    }
    /**
     * A pager: boundary pages pinned at each end, a window around the current
     * page, and an ellipsis wherever that leaves a gap.
     * Controlled or not, like `pf-input`: `page` is mutable, so leaving it alone
     * lets the element advance itself, and setting it on every `pfPageChange`
     * keeps the consumer in charge.
     */
    interface PfPagination {
        /**
          * Pages to pin at each end.
          * @default 1
         */
        "boundaryCount"?: number;
        /**
          * Disable every button. Reflected for the stylesheet.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible name for the navigation landmark.
          * @default 'Pagination'
         */
        "label"?: string;
        /**
          * Emitted with the page the user asked for, already clamped to the range.
         */
        "onPfPageChange"?: (event: PfPaginationCustomEvent<{ page: number }>) => void;
        /**
          * The current page, 1-based. Mutable so the element can advance itself.
          * @default 1
         */
        "page"?: number;
        /**
          * Show the previous/next buttons. Reflected for the stylesheet.
          * @default true
         */
        "showPrevNext"?: boolean;
        /**
          * Pages to show either side of the current one.
          * @default 1
         */
        "siblingCount"?: number;
        /**
          * How many pages there are in total.
          * @default 1
         */
        "totalPages"?: number;
    }
    /**
     * A horizontal determinate progress track.
     */
    interface PfProgressBar {
        /**
          * Accessible name.
         */
        "label"?: string;
        /**
          * The top of the scale.
          * @default 100
         */
        "max"?: number;
        /**
          * Show the percentage beside the track. Reflected for the stylesheet.
          * @default true
         */
        "showValue"?: boolean;
        /**
          * How far along, on the 0..max scale.
          * @default 0
         */
        "value"?: number;
    }
    /**
     * A circular determinate progress track.
     */
    interface PfProgressCircle {
        /**
          * Accessible name.
         */
        "label"?: string;
        /**
          * The top of the scale.
          * @default 100
         */
        "max"?: number;
        /**
          * Show the percentage in the middle. Reflected for the stylesheet.
          * @default true
         */
        "showValue"?: boolean;
        /**
          * Diameter in pixels.
          * @default 64
         */
        "size"?: number;
        /**
          * Ring thickness in pixels.
          * @default 6
         */
        "strokeWidth"?: number;
        /**
          * How far along, on the 0..max scale.
          * @default 0
         */
        "value"?: number;
    }
    /**
     * A scrollable region with a styled, non-overlaying scrollbar.
     */
    interface PfScrollArea {
        /**
          * Make the region keyboard-focusable so it can be scrolled with the arrow keys (WCAG 2.1.1). Set false when a focusable child already provides keyboard access.
          * @default true
         */
        "focusable"?: boolean;
        /**
          * Which axis scrolls. Reflected so the stylesheet can select on it.
          * @default 'vertical'
         */
        "orientation"?: PfScrollAreaOrientation;
    }
    /**
     * A form-associated range slider.
     * A native `<input type="range">`, as the React component is — the drag, the
     * keyboard stepping and the touch handling are all the browser's, and nothing
     * here reimplements them.
     */
    interface PfSlider {
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        /**
          * Submitted under this name. Reflected, because a form-associated element takes its submission name from the attribute, not this property.
         */
        "name"?: string;
        /**
          * Fires when the value is committed, like the native `change` event.
         */
        "onPfChange"?: (event: PfSliderCustomEvent<{ value: number }>) => void;
        /**
          * Fires as the user drags, like the native `input` event.
         */
        "onPfInput"?: (event: PfSliderCustomEvent<{ value: number }>) => void;
        /**
          * Show the current value beside the label. Reflected for the stylesheet.
          * @default true
         */
        "showValue"?: boolean;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * The control's value.
          * @default 0
         */
        "value"?: number;
    }
    /**
     * A form-associated on/off switch.
     * Built on a native checkbox with `role="switch"`, exactly as the React
     * component is: a switch is a checkbox whose two states are "on" and "off"
     * rather than "selected" and "not selected", and the role is the only
     * difference assistive technology needs.
     */
    interface PfSwitch {
        /**
          * Whether the switch is on. Reflected so the stylesheet can select on it.
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label, rendered in the same root so `for` actually associates.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * Fires when the user turns the switch on or off.
         */
        "onPfChange"?: (event: PfSwitchCustomEvent<{ checked: boolean; value: string }>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * What is submitted when on. Mirrors the native attribute, whose default is also `on` — a checkbox with no value still submits something.
          * @default 'on'
         */
        "value"?: string;
    }
    interface PfTag {
        /**
          * Accessible name for the remove button.
          * @default 'Remove tag'
         */
        "dismissLabel"?: string;
        /**
          * Show a button that removes the tag.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Fired when the remove button is pressed. The tag does not remove itself — whoever owns the list decides, exactly as the React `onDismiss` callback leaves it to the caller.
         */
        "onPfDismiss"?: (event: PfTagCustomEvent<void>) => void;
        /**
          * @default 'neutral'
         */
        "variant"?: PfTagVariant;
    }
    /**
     * A form-associated multi-line text control.
     * Shares `pf-input`'s field anatomy and form wiring; the control is a
     * `<textarea>` rather than an `<input>`, so it takes `rows` and resizes.
     */
    interface PfTextarea {
        /**
          * Hint text below the control.
         */
        "description"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message. Its presence is what marks the control invalid.
         */
        "error"?: string;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * Visible label. Rendered in the same root as the input, so `for` works.
         */
        "label"?: string;
        /**
          * Submitted under this name.  Reflected, because a form-associated custom element takes its submission name from the `name` *content attribute* -- not from this property. A framework wrapper that sets properties rather than attributes (the generated React bindings do) would otherwise leave the control nameless and absent from the submission, with every other sign of working.
         */
        "name"?: string;
        /**
          * Fires when the value is committed, like the native `change` event.
         */
        "onPfChange"?: (event: PfTextareaCustomEvent<{ value: string }>) => void;
        /**
          * Fires on every keystroke, like the native `input` event.
         */
        "onPfInput"?: (event: PfTextareaCustomEvent<{ value: string }>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * Visible rows. Mirrors the native attribute.
          * @default 4
         */
        "rows"?: number;
        /**
          * The control's value.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * A group of controls that is one tab stop from outside and navigated
     * internally with the arrow keys.
     * Items are matched in the light DOM, so a native `button`, `a[href]` or form
     * control works with no ceremony. A custom element is not a native control and
     * has to opt in with `data-toolbar-item` — `<pf-button data-toolbar-item>`.
     * Focusing it still reaches the real button inside, because `pf-button`
     * delegates focus.
     */
    interface PfToolbar {
        /**
          * Layout and arrow-key axis. Reflected so the stylesheet can select on it.
          * @default 'horizontal'
         */
        "orientation"?: PfToolbarOrientation;
    }
    /**
     * A rule between groups of toolbar controls.
     * `orientation` describes the toolbar it sits in, not the rule's own shape: a
     * horizontal toolbar gets a vertical hairline. `pf-toolbar` sets it on every
     * separator it contains, so a consumer does not have to — and cannot leave one
     * pointing the wrong way.
     */
    interface PfToolbarSeparator {
        /**
          * The axis of the toolbar this sits in. Reflected for the stylesheet.
          * @default 'horizontal'
         */
        "orientation"?: PfToolbarSeparatorOrientation;
    }
    /**
     * A compact button for toolbars and table rows, where the affordance is often
     * an icon alone.
     */
    interface PfUtilityButton {
        /**
          * Disable the button. Reflected so the stylesheet can select on it.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Accessible name. Required for an icon-only button, and also used as the native tooltip unless `tooltip` says otherwise.
         */
        "label"?: string;
        /**
          * Control size. Reflected so the stylesheet can select on it.
          * @default 'md'
         */
        "size"?: PfUtilityButtonSize;
        /**
          * Native tooltip text. Defaults to `label`.
         */
        "tooltip"?: string;
        /**
          * Mirrors the native attribute.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Colour treatment. Reflected so the stylesheet can select on it.
          * @default 'neutral'
         */
        "variant"?: PfUtilityButtonVariant;
    }
    /**
     * Hides content visually while keeping it available to screen readers and
     * other assistive technology. Use for labels, instructions and status text
     * that are implied visually but need to be announced.
     * The React component takes an `as` prop to choose its tag; a custom element's
     * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
     * hidden>Results</pf-visually-hidden></h2>` is still a heading named
     * "Results".
     */
    interface PfVisuallyHidden {
        /**
          * Reveal the content when it, or a descendant, receives keyboard focus — the classic "skip link" pattern. Reflected so the stylesheet can select on it.
          * @default false
         */
        "focusable"?: boolean;
    }

    interface PfAvatarAttributes {
        "src": string;
        "alt": string;
        "name": string;
        "size": PfAvatarSize;
        "status": PfAvatarStatus;
    }
    interface PfBadgeAttributes {
        "variant": PfBadgeVariant;
    }
    interface PfBadgeGroupAttributes {
        "label": string;
        "message": string;
        "color": PfBadgeGroupColor;
        "appearance": PfBadgeGroupAppearance;
        "badgePosition": PfBadgeGroupBadgePosition;
    }
    interface PfButtonAttributes {
        "variant": PfButtonVariant;
        "size": PfButtonSize;
        "fullWidth": boolean;
        "loading": boolean;
        "disabled": boolean;
        "type": PfButtonType;
        "label": string;
    }
    interface PfCheckboxAttributes {
        "name": string;
        "checked": boolean;
        "value": string;
        "label": string;
        "error": string;
        "required": boolean;
        "disabled": boolean;
    }
    interface PfContentDividerAttributes {
        "orientation": PfContentDividerOrientation;
        "inset": boolean;
    }
    interface PfCreditCardAttributes {
        "brand": PfCreditCardBrand;
        "cardNumber": string;
        "cardholderName": string;
        "expiry": string;
        "cvc": string;
        "masked": boolean;
    }
    interface PfIconAttributes {
        "name": string;
        "label": string;
    }
    interface PfInputAttributes {
        "name": string;
        "value": string;
        "type": PfInputType;
        "label": string;
        "description": string;
        "error": string;
        "placeholder": string;
        "required": boolean;
        "disabled": boolean;
        "readonly": boolean;
    }
    interface PfKbdAttributes {
        "size": PfKbdSize;
        "separator": string;
    }
    interface PfLoadingDotsAttributes {
        "size": PfLoadingDotsSize;
        "label": string;
    }
    interface PfLoadingSkeletonAttributes {
        "width": string;
        "height": string;
        "rounded": boolean;
        "label": string;
    }
    interface PfLoadingSpinnerAttributes {
        "size": number;
        "label": string;
    }
    interface PfPaginationAttributes {
        "page": number;
        "totalPages": number;
        "siblingCount": number;
        "boundaryCount": number;
        "showPrevNext": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface PfProgressBarAttributes {
        "value": number;
        "max": number;
        "showValue": boolean;
        "label": string;
    }
    interface PfProgressCircleAttributes {
        "value": number;
        "max": number;
        "size": number;
        "strokeWidth": number;
        "showValue": boolean;
        "label": string;
    }
    interface PfScrollAreaAttributes {
        "orientation": PfScrollAreaOrientation;
        "focusable": boolean;
    }
    interface PfSliderAttributes {
        "name": string;
        "value": number;
        "min": number;
        "max": number;
        "step": number;
        "label": string;
        "description": string;
        "error": string;
        "showValue": boolean;
        "disabled": boolean;
    }
    interface PfSwitchAttributes {
        "name": string;
        "checked": boolean;
        "value": string;
        "label": string;
        "error": string;
        "required": boolean;
        "disabled": boolean;
    }
    interface PfTagAttributes {
        "variant": PfTagVariant;
        "dismissible": boolean;
        "dismissLabel": string;
    }
    interface PfTextareaAttributes {
        "name": string;
        "value": string;
        "rows": number;
        "label": string;
        "description": string;
        "error": string;
        "placeholder": string;
        "required": boolean;
        "disabled": boolean;
        "readonly": boolean;
    }
    interface PfToolbarAttributes {
        "orientation": PfToolbarOrientation;
    }
    interface PfToolbarSeparatorAttributes {
        "orientation": PfToolbarSeparatorOrientation;
    }
    interface PfUtilityButtonAttributes {
        "variant": PfUtilityButtonVariant;
        "size": PfUtilityButtonSize;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "label": string;
        "tooltip": string;
    }
    interface PfVisuallyHiddenAttributes {
        "focusable": boolean;
    }

    interface IntrinsicElements {
        "pf-avatar": Omit<PfAvatar, keyof PfAvatarAttributes> & { [K in keyof PfAvatar & keyof PfAvatarAttributes]?: PfAvatar[K] } & { [K in keyof PfAvatar & keyof PfAvatarAttributes as `attr:${K}`]?: PfAvatarAttributes[K] } & { [K in keyof PfAvatar & keyof PfAvatarAttributes as `prop:${K}`]?: PfAvatar[K] };
        "pf-badge": Omit<PfBadge, keyof PfBadgeAttributes> & { [K in keyof PfBadge & keyof PfBadgeAttributes]?: PfBadge[K] } & { [K in keyof PfBadge & keyof PfBadgeAttributes as `attr:${K}`]?: PfBadgeAttributes[K] } & { [K in keyof PfBadge & keyof PfBadgeAttributes as `prop:${K}`]?: PfBadge[K] };
        "pf-badge-group": Omit<PfBadgeGroup, keyof PfBadgeGroupAttributes> & { [K in keyof PfBadgeGroup & keyof PfBadgeGroupAttributes]?: PfBadgeGroup[K] } & { [K in keyof PfBadgeGroup & keyof PfBadgeGroupAttributes as `attr:${K}`]?: PfBadgeGroupAttributes[K] } & { [K in keyof PfBadgeGroup & keyof PfBadgeGroupAttributes as `prop:${K}`]?: PfBadgeGroup[K] };
        "pf-button": Omit<PfButton, keyof PfButtonAttributes> & { [K in keyof PfButton & keyof PfButtonAttributes]?: PfButton[K] } & { [K in keyof PfButton & keyof PfButtonAttributes as `attr:${K}`]?: PfButtonAttributes[K] } & { [K in keyof PfButton & keyof PfButtonAttributes as `prop:${K}`]?: PfButton[K] };
        "pf-card": PfCard;
        "pf-card-content": PfCardContent;
        "pf-card-footer": PfCardFooter;
        "pf-card-header": PfCardHeader;
        "pf-checkbox": Omit<PfCheckbox, keyof PfCheckboxAttributes> & { [K in keyof PfCheckbox & keyof PfCheckboxAttributes]?: PfCheckbox[K] } & { [K in keyof PfCheckbox & keyof PfCheckboxAttributes as `attr:${K}`]?: PfCheckboxAttributes[K] } & { [K in keyof PfCheckbox & keyof PfCheckboxAttributes as `prop:${K}`]?: PfCheckbox[K] };
        "pf-content-divider": Omit<PfContentDivider, keyof PfContentDividerAttributes> & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes]?: PfContentDivider[K] } & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes as `attr:${K}`]?: PfContentDividerAttributes[K] } & { [K in keyof PfContentDivider & keyof PfContentDividerAttributes as `prop:${K}`]?: PfContentDivider[K] };
        "pf-credit-card": Omit<PfCreditCard, keyof PfCreditCardAttributes> & { [K in keyof PfCreditCard & keyof PfCreditCardAttributes]?: PfCreditCard[K] } & { [K in keyof PfCreditCard & keyof PfCreditCardAttributes as `attr:${K}`]?: PfCreditCardAttributes[K] } & { [K in keyof PfCreditCard & keyof PfCreditCardAttributes as `prop:${K}`]?: PfCreditCard[K] };
        "pf-icon": Omit<PfIcon, keyof PfIconAttributes> & { [K in keyof PfIcon & keyof PfIconAttributes]?: PfIcon[K] } & { [K in keyof PfIcon & keyof PfIconAttributes as `attr:${K}`]?: PfIconAttributes[K] } & { [K in keyof PfIcon & keyof PfIconAttributes as `prop:${K}`]?: PfIcon[K] } & OneOf<"name", PfIcon["name"], PfIconAttributes["name"]>;
        "pf-input": Omit<PfInput, keyof PfInputAttributes> & { [K in keyof PfInput & keyof PfInputAttributes]?: PfInput[K] } & { [K in keyof PfInput & keyof PfInputAttributes as `attr:${K}`]?: PfInputAttributes[K] } & { [K in keyof PfInput & keyof PfInputAttributes as `prop:${K}`]?: PfInput[K] };
        "pf-kbd": Omit<PfKbd, keyof PfKbdAttributes> & { [K in keyof PfKbd & keyof PfKbdAttributes]?: PfKbd[K] } & { [K in keyof PfKbd & keyof PfKbdAttributes as `attr:${K}`]?: PfKbdAttributes[K] } & { [K in keyof PfKbd & keyof PfKbdAttributes as `prop:${K}`]?: PfKbd[K] };
        "pf-loading-dots": Omit<PfLoadingDots, keyof PfLoadingDotsAttributes> & { [K in keyof PfLoadingDots & keyof PfLoadingDotsAttributes]?: PfLoadingDots[K] } & { [K in keyof PfLoadingDots & keyof PfLoadingDotsAttributes as `attr:${K}`]?: PfLoadingDotsAttributes[K] } & { [K in keyof PfLoadingDots & keyof PfLoadingDotsAttributes as `prop:${K}`]?: PfLoadingDots[K] };
        "pf-loading-skeleton": Omit<PfLoadingSkeleton, keyof PfLoadingSkeletonAttributes> & { [K in keyof PfLoadingSkeleton & keyof PfLoadingSkeletonAttributes]?: PfLoadingSkeleton[K] } & { [K in keyof PfLoadingSkeleton & keyof PfLoadingSkeletonAttributes as `attr:${K}`]?: PfLoadingSkeletonAttributes[K] } & { [K in keyof PfLoadingSkeleton & keyof PfLoadingSkeletonAttributes as `prop:${K}`]?: PfLoadingSkeleton[K] };
        "pf-loading-spinner": Omit<PfLoadingSpinner, keyof PfLoadingSpinnerAttributes> & { [K in keyof PfLoadingSpinner & keyof PfLoadingSpinnerAttributes]?: PfLoadingSpinner[K] } & { [K in keyof PfLoadingSpinner & keyof PfLoadingSpinnerAttributes as `attr:${K}`]?: PfLoadingSpinnerAttributes[K] } & { [K in keyof PfLoadingSpinner & keyof PfLoadingSpinnerAttributes as `prop:${K}`]?: PfLoadingSpinner[K] };
        "pf-pagination": Omit<PfPagination, keyof PfPaginationAttributes> & { [K in keyof PfPagination & keyof PfPaginationAttributes]?: PfPagination[K] } & { [K in keyof PfPagination & keyof PfPaginationAttributes as `attr:${K}`]?: PfPaginationAttributes[K] } & { [K in keyof PfPagination & keyof PfPaginationAttributes as `prop:${K}`]?: PfPagination[K] };
        "pf-progress-bar": Omit<PfProgressBar, keyof PfProgressBarAttributes> & { [K in keyof PfProgressBar & keyof PfProgressBarAttributes]?: PfProgressBar[K] } & { [K in keyof PfProgressBar & keyof PfProgressBarAttributes as `attr:${K}`]?: PfProgressBarAttributes[K] } & { [K in keyof PfProgressBar & keyof PfProgressBarAttributes as `prop:${K}`]?: PfProgressBar[K] };
        "pf-progress-circle": Omit<PfProgressCircle, keyof PfProgressCircleAttributes> & { [K in keyof PfProgressCircle & keyof PfProgressCircleAttributes]?: PfProgressCircle[K] } & { [K in keyof PfProgressCircle & keyof PfProgressCircleAttributes as `attr:${K}`]?: PfProgressCircleAttributes[K] } & { [K in keyof PfProgressCircle & keyof PfProgressCircleAttributes as `prop:${K}`]?: PfProgressCircle[K] };
        "pf-scroll-area": Omit<PfScrollArea, keyof PfScrollAreaAttributes> & { [K in keyof PfScrollArea & keyof PfScrollAreaAttributes]?: PfScrollArea[K] } & { [K in keyof PfScrollArea & keyof PfScrollAreaAttributes as `attr:${K}`]?: PfScrollAreaAttributes[K] } & { [K in keyof PfScrollArea & keyof PfScrollAreaAttributes as `prop:${K}`]?: PfScrollArea[K] };
        "pf-slider": Omit<PfSlider, keyof PfSliderAttributes> & { [K in keyof PfSlider & keyof PfSliderAttributes]?: PfSlider[K] } & { [K in keyof PfSlider & keyof PfSliderAttributes as `attr:${K}`]?: PfSliderAttributes[K] } & { [K in keyof PfSlider & keyof PfSliderAttributes as `prop:${K}`]?: PfSlider[K] };
        "pf-switch": Omit<PfSwitch, keyof PfSwitchAttributes> & { [K in keyof PfSwitch & keyof PfSwitchAttributes]?: PfSwitch[K] } & { [K in keyof PfSwitch & keyof PfSwitchAttributes as `attr:${K}`]?: PfSwitchAttributes[K] } & { [K in keyof PfSwitch & keyof PfSwitchAttributes as `prop:${K}`]?: PfSwitch[K] };
        "pf-tag": Omit<PfTag, keyof PfTagAttributes> & { [K in keyof PfTag & keyof PfTagAttributes]?: PfTag[K] } & { [K in keyof PfTag & keyof PfTagAttributes as `attr:${K}`]?: PfTagAttributes[K] } & { [K in keyof PfTag & keyof PfTagAttributes as `prop:${K}`]?: PfTag[K] };
        "pf-textarea": Omit<PfTextarea, keyof PfTextareaAttributes> & { [K in keyof PfTextarea & keyof PfTextareaAttributes]?: PfTextarea[K] } & { [K in keyof PfTextarea & keyof PfTextareaAttributes as `attr:${K}`]?: PfTextareaAttributes[K] } & { [K in keyof PfTextarea & keyof PfTextareaAttributes as `prop:${K}`]?: PfTextarea[K] };
        "pf-toolbar": Omit<PfToolbar, keyof PfToolbarAttributes> & { [K in keyof PfToolbar & keyof PfToolbarAttributes]?: PfToolbar[K] } & { [K in keyof PfToolbar & keyof PfToolbarAttributes as `attr:${K}`]?: PfToolbarAttributes[K] } & { [K in keyof PfToolbar & keyof PfToolbarAttributes as `prop:${K}`]?: PfToolbar[K] };
        "pf-toolbar-separator": Omit<PfToolbarSeparator, keyof PfToolbarSeparatorAttributes> & { [K in keyof PfToolbarSeparator & keyof PfToolbarSeparatorAttributes]?: PfToolbarSeparator[K] } & { [K in keyof PfToolbarSeparator & keyof PfToolbarSeparatorAttributes as `attr:${K}`]?: PfToolbarSeparatorAttributes[K] } & { [K in keyof PfToolbarSeparator & keyof PfToolbarSeparatorAttributes as `prop:${K}`]?: PfToolbarSeparator[K] };
        "pf-utility-button": Omit<PfUtilityButton, keyof PfUtilityButtonAttributes> & { [K in keyof PfUtilityButton & keyof PfUtilityButtonAttributes]?: PfUtilityButton[K] } & { [K in keyof PfUtilityButton & keyof PfUtilityButtonAttributes as `attr:${K}`]?: PfUtilityButtonAttributes[K] } & { [K in keyof PfUtilityButton & keyof PfUtilityButtonAttributes as `prop:${K}`]?: PfUtilityButton[K] };
        "pf-visually-hidden": Omit<PfVisuallyHidden, keyof PfVisuallyHiddenAttributes> & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes]?: PfVisuallyHidden[K] } & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes as `attr:${K}`]?: PfVisuallyHiddenAttributes[K] } & { [K in keyof PfVisuallyHidden & keyof PfVisuallyHiddenAttributes as `prop:${K}`]?: PfVisuallyHidden[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pf-avatar": LocalJSX.IntrinsicElements["pf-avatar"] & JSXBase.HTMLAttributes<HTMLPfAvatarElement>;
            "pf-badge": LocalJSX.IntrinsicElements["pf-badge"] & JSXBase.HTMLAttributes<HTMLPfBadgeElement>;
            /**
             * A badge joined to a line of text, sharing one rounded outline — the
             * "2 new · See what's changed" pattern.
             */
            "pf-badge-group": LocalJSX.IntrinsicElements["pf-badge-group"] & JSXBase.HTMLAttributes<HTMLPfBadgeGroupElement>;
            "pf-button": LocalJSX.IntrinsicElements["pf-button"] & JSXBase.HTMLAttributes<HTMLPfButtonElement>;
            /**
             * A surface that groups related content.
             * The React library's `Card` / `CardHeader` / `CardContent` / `CardFooter` map
             * to four elements rather than to one element with named slots. Named slots
             * would need a slot controller to know whether to render each wrapper at all —
             * an unslotted `header` would otherwise leave a padded, bordered empty strip.
             * Separate elements have no such state: the consumer writing
             * `<pf-card-header>` *is* the signal.
             */
            "pf-card": LocalJSX.IntrinsicElements["pf-card"] & JSXBase.HTMLAttributes<HTMLPfCardElement>;
            /**
             * The body section of a `pf-card`.
             */
            "pf-card-content": LocalJSX.IntrinsicElements["pf-card-content"] & JSXBase.HTMLAttributes<HTMLPfCardContentElement>;
            /**
             * The bottom section of a `pf-card`, separated from what precedes it by a rule.
             * Lays its children out in a row, which is what makes it the natural home for
             * a card's actions.
             */
            "pf-card-footer": LocalJSX.IntrinsicElements["pf-card-footer"] & JSXBase.HTMLAttributes<HTMLPfCardFooterElement>;
            /**
             * The top section of a `pf-card`, separated from what follows by a rule.
             */
            "pf-card-header": LocalJSX.IntrinsicElements["pf-card-header"] & JSXBase.HTMLAttributes<HTMLPfCardHeaderElement>;
            /**
             * A form-associated checkbox.
             */
            "pf-checkbox": LocalJSX.IntrinsicElements["pf-checkbox"] & JSXBase.HTMLAttributes<HTMLPfCheckboxElement>;
            /**
             * A rule that separates content, optionally labelled.
             */
            "pf-content-divider": LocalJSX.IntrinsicElements["pf-content-divider"] & JSXBase.HTMLAttributes<HTMLPfContentDividerElement>;
            /**
             * A card-shaped display of payment details. Presentational only — it stores
             * nothing and submits nothing.
             */
            "pf-credit-card": LocalJSX.IntrinsicElements["pf-credit-card"] & JSXBase.HTMLAttributes<HTMLPfCreditCardElement>;
            "pf-icon": LocalJSX.IntrinsicElements["pf-icon"] & JSXBase.HTMLAttributes<HTMLPfIconElement>;
            /**
             * A form-associated text input.
             * `formAssociated` plus `ElementInternals` is what makes this participate in a
             * real `<form>`: the value reaches `FormData`, constraint validation works, and
             * Angular's generated value accessor has something to bind to. A plain
             * `<input>` inside a shadow root does none of that.
             */
            "pf-input": LocalJSX.IntrinsicElements["pf-input"] & JSXBase.HTMLAttributes<HTMLPfInputElement>;
            "pf-kbd": LocalJSX.IntrinsicElements["pf-kbd"] & JSXBase.HTMLAttributes<HTMLPfKbdElement>;
            /**
             * Three pulsing dots, for an indeterminate wait in a tight space.
             */
            "pf-loading-dots": LocalJSX.IntrinsicElements["pf-loading-dots"] & JSXBase.HTMLAttributes<HTMLPfLoadingDotsElement>;
            /**
             * A shimmering placeholder for content that has not arrived.
             */
            "pf-loading-skeleton": LocalJSX.IntrinsicElements["pf-loading-skeleton"] & JSXBase.HTMLAttributes<HTMLPfLoadingSkeletonElement>;
            /**
             * An indeterminate spinner.
             */
            "pf-loading-spinner": LocalJSX.IntrinsicElements["pf-loading-spinner"] & JSXBase.HTMLAttributes<HTMLPfLoadingSpinnerElement>;
            /**
             * A pager: boundary pages pinned at each end, a window around the current
             * page, and an ellipsis wherever that leaves a gap.
             * Controlled or not, like `pf-input`: `page` is mutable, so leaving it alone
             * lets the element advance itself, and setting it on every `pfPageChange`
             * keeps the consumer in charge.
             */
            "pf-pagination": LocalJSX.IntrinsicElements["pf-pagination"] & JSXBase.HTMLAttributes<HTMLPfPaginationElement>;
            /**
             * A horizontal determinate progress track.
             */
            "pf-progress-bar": LocalJSX.IntrinsicElements["pf-progress-bar"] & JSXBase.HTMLAttributes<HTMLPfProgressBarElement>;
            /**
             * A circular determinate progress track.
             */
            "pf-progress-circle": LocalJSX.IntrinsicElements["pf-progress-circle"] & JSXBase.HTMLAttributes<HTMLPfProgressCircleElement>;
            /**
             * A scrollable region with a styled, non-overlaying scrollbar.
             */
            "pf-scroll-area": LocalJSX.IntrinsicElements["pf-scroll-area"] & JSXBase.HTMLAttributes<HTMLPfScrollAreaElement>;
            /**
             * A form-associated range slider.
             * A native `<input type="range">`, as the React component is — the drag, the
             * keyboard stepping and the touch handling are all the browser's, and nothing
             * here reimplements them.
             */
            "pf-slider": LocalJSX.IntrinsicElements["pf-slider"] & JSXBase.HTMLAttributes<HTMLPfSliderElement>;
            /**
             * A form-associated on/off switch.
             * Built on a native checkbox with `role="switch"`, exactly as the React
             * component is: a switch is a checkbox whose two states are "on" and "off"
             * rather than "selected" and "not selected", and the role is the only
             * difference assistive technology needs.
             */
            "pf-switch": LocalJSX.IntrinsicElements["pf-switch"] & JSXBase.HTMLAttributes<HTMLPfSwitchElement>;
            "pf-tag": LocalJSX.IntrinsicElements["pf-tag"] & JSXBase.HTMLAttributes<HTMLPfTagElement>;
            /**
             * A form-associated multi-line text control.
             * Shares `pf-input`'s field anatomy and form wiring; the control is a
             * `<textarea>` rather than an `<input>`, so it takes `rows` and resizes.
             */
            "pf-textarea": LocalJSX.IntrinsicElements["pf-textarea"] & JSXBase.HTMLAttributes<HTMLPfTextareaElement>;
            /**
             * A group of controls that is one tab stop from outside and navigated
             * internally with the arrow keys.
             * Items are matched in the light DOM, so a native `button`, `a[href]` or form
             * control works with no ceremony. A custom element is not a native control and
             * has to opt in with `data-toolbar-item` — `<pf-button data-toolbar-item>`.
             * Focusing it still reaches the real button inside, because `pf-button`
             * delegates focus.
             */
            "pf-toolbar": LocalJSX.IntrinsicElements["pf-toolbar"] & JSXBase.HTMLAttributes<HTMLPfToolbarElement>;
            /**
             * A rule between groups of toolbar controls.
             * `orientation` describes the toolbar it sits in, not the rule's own shape: a
             * horizontal toolbar gets a vertical hairline. `pf-toolbar` sets it on every
             * separator it contains, so a consumer does not have to — and cannot leave one
             * pointing the wrong way.
             */
            "pf-toolbar-separator": LocalJSX.IntrinsicElements["pf-toolbar-separator"] & JSXBase.HTMLAttributes<HTMLPfToolbarSeparatorElement>;
            /**
             * A compact button for toolbars and table rows, where the affordance is often
             * an icon alone.
             */
            "pf-utility-button": LocalJSX.IntrinsicElements["pf-utility-button"] & JSXBase.HTMLAttributes<HTMLPfUtilityButtonElement>;
            /**
             * Hides content visually while keeping it available to screen readers and
             * other assistive technology. Use for labels, instructions and status text
             * that are implied visually but need to be announced.
             * The React component takes an `as` prop to choose its tag; a custom element's
             * tag is fixed, so wrap this instead of configuring it — `<h2><pf-visually-
             * hidden>Results</pf-visually-hidden></h2>` is still a heading named
             * "Results".
             */
            "pf-visually-hidden": LocalJSX.IntrinsicElements["pf-visually-hidden"] & JSXBase.HTMLAttributes<HTMLPfVisuallyHiddenElement>;
        }
    }
}
