import { useCallback, useEffect, useState } from 'react';
import { DEFAULTS } from '../tokens/defaults';

export type Overrides = Record<string, string>;

function encodeOverrides(o: Overrides): string {
  return btoa(JSON.stringify(o));
}

function decodeOverrides(encoded: string): Overrides {
  try {
    return JSON.parse(atob(encoded));
  } catch {
    return {};
  }
}

function loadFromUrl(): Overrides {
  const params = new URLSearchParams(window.location.hash.slice(1));
  const encoded = params.get('theme');
  return encoded ? decodeOverrides(encoded) : {};
}

// Track every var we've ever written so we can clear it on the next apply,
// even if it's not in DEFAULTS (e.g. --pf-* component vars).
const appliedVars = new Set<string>();

function applyToRoot(overrides: Overrides) {
  const root = document.documentElement;
  // Clear everything previously applied (covers --color-*, --pf-*, etc.)
  appliedVars.forEach((v) => root.style.removeProperty(v));
  appliedVars.clear();
  // Apply the current overrides and remember what we set
  Object.entries(overrides).forEach(([v, val]) => {
    root.style.setProperty(v, val);
    appliedVars.add(v);
  });
}

export function useTheme() {
  const [overrides, setOverrides] = useState<Overrides>(loadFromUrl);
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    applyToRoot(overrides);
  }, [overrides]);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.setAttribute('data-theme', 'dark');
    } else {
      document.documentElement.removeAttribute('data-theme');
    }
  }, [darkMode]);

  useEffect(() => {
    const hash = Object.keys(overrides).length > 0 ? `#theme=${encodeOverrides(overrides)}` : '';
    window.history.replaceState(null, '', hash || window.location.pathname);
  }, [overrides]);

  const set = useCallback((varName: string, value: string) => {
    setOverrides((prev) => ({ ...prev, [varName]: value }));
  }, []);

  const resetVar = useCallback((varName: string) => {
    setOverrides((prev) => {
      const next = { ...prev };
      delete next[varName];
      return next;
    });
  }, []);

  const resetAll = useCallback(() => setOverrides({}), []);

  const getValue = useCallback(
    (varName: string) => overrides[varName] ?? DEFAULTS[varName] ?? '',
    [overrides],
  );

  const isModified = useCallback((varName: string) => varName in overrides, [overrides]);

  const exportCSS = useCallback((): string => {
    if (Object.keys(overrides).length === 0) {
      return '/* No overrides — your theme matches the Pitchfork UI defaults. */';
    }
    const lines = Object.entries(overrides)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join('\n');
    return [
      '/* Generated by Pitchfork UI Theme Builder */',
      '/* Import after @pitchfork-ui/react/styles.css */',
      '',
      ':root {',
      lines,
      '}',
    ].join('\n');
  }, [overrides]);

  return {
    overrides,
    set,
    resetVar,
    resetAll,
    getValue,
    isModified,
    exportCSS,
    darkMode,
    setDarkMode,
  };
}

export type ThemeState = ReturnType<typeof useTheme>;
